### ISSUE TITLE
Compiling error WiFiClientMQTTSECURE' does not name a type

### ISSUE THREAD

**Issue by mpuff** [weigu1/SmartyReader#2]
Hello,

when I try to compile with mqttsecure I get an error in v1.5:

SmartyReader_v1_5:154:3: error: 'WiFiClientMQTTSECURE' does not name a type
  154 |   WiFiClientMQTTSECURE espClient;
      |   ^~~~~~~~~~~~~~~~~~~~
SmartyReader_v1_5:161:25: error: 'espClient' was not declared in this scope; did you mean 'DNSClient'?
  161 | PubSubClient mqttClient(espClient);

**Comment by weigu1** [comment]
This is corrected in the new version
